RESDIR = f"{ACT_CVCF_ROOT}/results"
LOGDIR = f"{ACT_CVCF_ROOT}/logs"
TEMPDIR = f"{ACT_CVCF_ROOT}/temp"
PREPDIR = f"{ACT_PVCF_ROOT}/results"

CONVERT_PLINK_OUT_PFX = f"{TEMPDIR}/plink/imputed_chr{{chromosome}}"
rule vcf_to_plink:
    container: PLINK_IMG
    input:
        vcf=M_VCF_OUT_PFX,
        tbi=f"{M_VCF_OUT_PFX}.tbi",
    output:
        bed=temp(f"{CONVERT_PLINK_OUT_PFX}.bed"),
        bim=temp(f"{CONVERT_PLINK_OUT_PFX}.bim"),
        fam=temp(f"{CONVERT_PLINK_OUT_PFX}.fam"),
    log: f"{LOGDIR}/vcf_to_plink/{{chromosome}}.log"
    shell:
        """
        outdir=plinktemp.chr{wildcards.chromosome}
        pfx=$outdir/plink
        mkdir -p $outdir
        plink --vcf {input.vcf} \
            --make-bed \
            --out $pfx
        mv $pfx.bed {output.bed}
        mv $pfx.bim {output.bim}
        mv $pfx.fam {output.fam}
        mv $pfx.log {log}
        rm -rf $outdir
        """

rule merge_list:
    input:
        bed=expand(rules.vcf_to_plink.output.bed, chromosome=CHROMOSOMES),
        bim=expand(rules.vcf_to_plink.output.bim, chromosome=CHROMOSOMES),
        fam=expand(rules.vcf_to_plink.output.fam, chromosome=CHROMOSOMES),
    output:
        merge_list=temp(f"{TEMPDIR}/merge_list.txt"),
    log:
        f"{LOGDIR}/merge_list.log"
    shell:
        """
        echo '{input.bed} ' | sed 's/\\.bed /\\n/g' > {output.merge_list} 2> {log}
        """

PLINK_MERGE_PFX = f"{RESDIR}/act_imputed"
rule plink_merge:
    container: PLINK_IMG
    input:
        bed=expand(rules.vcf_to_plink.output.bed, chromosome=CHROMOSOMES),
        bim=expand(rules.vcf_to_plink.output.bim, chromosome=CHROMOSOMES),
        fam=expand(rules.vcf_to_plink.output.fam, chromosome=CHROMOSOMES),
        merge_list=rules.merge_list.output,
    output:
        bed=f"{PLINK_MERGE_PFX}.bed",
        bim=f"{PLINK_MERGE_PFX}.bim",
        fam=f"{PLINK_MERGE_PFX}.fam",
    log:
        f"{LOGDIR}/plink_merge.log"
    shell:
        """
        outdir=bmergetemp
        mkdir -p $outdir
        pfx=$outdir/plink
        plink \
        --merge-list {input.merge_list} \
        --make-bed \
        --out $pfx
        mv $pfx.bed {output.bed}
        mv $pfx.bim {output.bim}
        mv $pfx.fam {output.fam}
        mv $pfx.log {log}
        rm -rf $outdir
        """
