module serpent:
    #snakefile: github("broomej/serpent", path="workflow/Snakefile", tag=config.get("serpent_version"))
    snakefile: github("broomej/serpent", path="workflow/Snakefile", commit="1fbad34925a23e2efeb8123dad1af20c28b00f35")

PREPDIR = f"{config['project_root']['act']['data_prep']}/results"
ROOTDIR = config["project_root"]["act"]["convert_vcf"]
RESDIR = f"{ROOTDIR}/results"
LOGDIR = f"{ROOTDIR}/logs"
TEMPDIR = f"{ROOTDIR}/temp"

F_VCF=f"{PREPDIR}/vcf/chr{{chromosome}}_filtered.vcf.gz"
rule get_ids:
    container: BCFTOOLS_IMG
    input:
        vcf=F_VCF,
        tbi=F_VCF + ".tbi",
    output: temp(f"{TEMPDIR}/typed_ids/{{chromosome}}_typed_ids.txt"),
    log: f"{LOGDIR}/get_ids/{{chromosome}}.log"
    shell:
        """
        bcftools query -l {input.vcf} > {output} 2> {log}
        """

rule combine_ids:
    input: expand(rules.get_ids.output, cohort=COHORTS, chromosome=CHROMOSOMES)
    output: f"{RESDIR}/typed_ids.txt"
    log: f"{LOGDIR}/combine_ids.log"
    shell:
        """
        cat {input} > {output} 2> {log}
        """

rule get_bps_samples:
    container: SHINY_VERSE_IMG
    input:
        bps=f"{ACT_DATA_DIR}/act_bps.txt",
        xwalk=f"{ACT_DATA_DIR}/ACT_ID_xwalk.csv",
        typed_ids=rules.combine_ids.output,
    output:
        txt=f"{RESDIR}/np_ids.txt",
        rds=f"{RESDIR}/np_ids.rds",
        ids_matched=f"{RESDIR}/ids_matched.csv",
    log: f"{LOGDIR}/get_bps_samples.log"
    script: "scripts/extract_ids.R"

CONVERT_PLINK_OUT_PFX = f"{TEMPDIR}/plink/np_imputed_chr{{chromosome}}"
rule vcf_to_plink:
    container: PLINK_IMG
    input:
        vcf=M_VCF_OUT_PFX,
        tbi=M_VCF_OUT_PFX + ".tbi",
        ids=rules.get_bps_samples.output.txt,
    output:
        bed=temp(CONVERT_PLINK_OUT_PFX + ".bed"),
        bim=temp(CONVERT_PLINK_OUT_PFX + ".bim"),
        fam=temp(CONVERT_PLINK_OUT_PFX + ".fam"),
    params:
        out_pfx=CONVERT_PLINK_OUT_PFX,
    log: f"{LOGDIR}/vcf_to_plink/{{chromosome}}.log"
    shell:
        """
        plink --vcf {input.vcf} \
            --keep {input.ids} \
            --make-bed \
            --out {params.out_pfx}
        mv {params.out_pfx}.log {log}
        """

rule merge_list:
    input:
        bed=expand(rules.vcf_to_plink.output.bed, chromosome=CHROMOSOMES),
        bim=expand(rules.vcf_to_plink.output.bim, chromosome=CHROMOSOMES),
        fam=expand(rules.vcf_to_plink.output.fam, chromosome=CHROMOSOMES),
    output:
        merge_list=temp(f"{TEMPDIR}/merge_list.txt"),
    log:
        f"{LOGDIR}/merge_list.log"
    shell:
        """
        echo '{input.bed} ' | sed 's/\\.bed /\\n/g' > {output.merge_list} 2> {log}
        """

PLINK_MERGE_PFX = f"{RESDIR}/act_np_imputed"
rule plink_merge:
    container: PLINK_IMG
    input:
        bed=expand(rules.vcf_to_plink.output.bed, chromosome=CHROMOSOMES),
        bim=expand(rules.vcf_to_plink.output.bim, chromosome=CHROMOSOMES),
        fam=expand(rules.vcf_to_plink.output.fam, chromosome=CHROMOSOMES),
        merge_list=rules.merge_list.output,
    output:
        bed=PLINK_MERGE_PFX + ".bed",
        bim=PLINK_MERGE_PFX + ".bim",
        fam=PLINK_MERGE_PFX + ".fam",
    log:
        f"{LOGDIR}/plink_merge.log"
    params:
        out_pfx=PLINK_MERGE_PFX,
    shell:
        """
        plink \
        --merge-list {input.merge_list} \
        --make-bed \
        --out {params.out_pfx}
        mv {params.out_pfx}.log {log}
        """
