CONVERT_PLINK_OUT_PFX = "temp/plink/imputed_chr{chromosome}"
M_VCF_OUT_PFX = f"{config["outdir"]["act"]["process_vcf"]}/results/vcf/chr{{chromosome}}_filtered.vcf.gz"
rule vcf_to_plink:
    container: config["images"]["plink"]
    input:
        vcf=expand(M_VCF_OUT_PFX, chromosome = config["CHROMOSOMES"]),
        tbi=expand(f"{M_VCF_OUT_PFX}.tbi", chromosome = config["CHROMOSOMES"]), 
    output:
        bed=temp(f"{CONVERT_PLINK_OUT_PFX}.bed"),
        bim=temp(f"{CONVERT_PLINK_OUT_PFX}.bim"),
        fam=temp(f"{CONVERT_PLINK_OUT_PFX}.fam"),
    log: "logs/vcf_to_plink/{chromosome}.log"
    shell:
        """
        outdir=plinktemp.chr{wildcards.chromosome}
        pfx=$outdir/plink
        mkdir -p $outdir
        plink --vcf {input.vcf} \
            --make-bed \
            --out $pfx
        mv $pfx.bed {output.bed}
        mv $pfx.bim {output.bim}
        mv $pfx.fam {output.fam}
        mv $pfx.log {log}
        rm -rf $outdir
        """

rule merge_list:
    input:
        bed=expand(rules.vcf_to_plink.output.bed, chromosome = config["CHROMOSOMES"]),
        bim=expand(rules.vcf_to_plink.output.bim, chromosome = config["CHROMOSOMES"]),
        fam=expand(rules.vcf_to_plink.output.fam, chromosome = config["CHROMOSOMES"]),
    output:
        merge_list=temp("temp/merge_list.txt"),
    log: "logs/merge_list.log"
    shell:
        """
        echo '{input.bed} ' | sed 's/\\.bed /\\n/g' > {output.merge_list} 2> {log}
        """

PLINK_MERGE_PFX = "results/act_imputed"
rule plink_merge:
    container: config["images"]["plink"]
    input:
        bed=expand(rules.vcf_to_plink.output.bed, chromosome = config["CHROMOSOMES"]),
        bim=expand(rules.vcf_to_plink.output.bim, chromosome = config["CHROMOSOMES"]),
        fam=expand(rules.vcf_to_plink.output.fam, chromosome = config["CHROMOSOMES"]),
        merge_list=rules.merge_list.output,
    output:
        bed=f"{PLINK_MERGE_PFX}.bed",
        bim=f"{PLINK_MERGE_PFX}.bim",
        fam=f"{PLINK_MERGE_PFX}.fam",
    log: "logs/plink_merge.log"
    shell:
        """
        outdir=bmergetemp
        mkdir -p $outdir
        pfx=$outdir/plink
        plink \
        --merge-list {input.merge_list} \
        --make-bed \
        --out $pfx
        mv $pfx.bed {output.bed}
        mv $pfx.bim {output.bim}
        mv $pfx.fam {output.fam}
        mv $pfx.log {log}
        rm -rf $outdir
        """
